version: '2'

services:
  jupyter:
    build: ./jupyterhub
    ports:
      - "8888:8888"
    environment:
      - "CLOUDSDK_CONFIG=/tmp/.config"
      - "DATALAB_ROOT==/tmp/.config"
      - "PIP_CACHE_DIR=/exchange/pip_cache"
      - "XDG_CACHE_HOME=/exchange/pip_cache"
    volumes:
      - ./data/notebooks:/home/jovyan/work
      - ./data/original:/exchange
